name: export_video_frame
description: A Flutter plugin for iOS and Android for exporting picture from video file.
version: 0.0.7
homepage: https://github.com/animeng/flutter_export_video_frame

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  media_info: ^0.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mengtnt.export_video_frame
        pluginClass: ExportVideoFramePlugin
      ios:
        pluginClass: ExportVideoFramePlugin